# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"D\n\nAddRequest\x12\x11\n\x04num1\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04num2\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_num1B\x07\n\x05_num2\"I\n\x0fsubtractRequest\x12\x11\n\x04num1\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04num2\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_num1B\x07\n\x05_num2\"-\n\x0bResultReply\x12\x13\n\x06number\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\t\n\x07_number2W\n\x03\x43\x61l\x12\"\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.ResultReply\"\x00\x12,\n\x08subtract\x12\x10.subtractRequest\x1a\x0c.ResultReply\"\x00\x62\x06proto3'
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='AddRequest.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='AddRequest.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_num1', full_name='AddRequest._num1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_num2', full_name='AddRequest._num2',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=14,
  serialized_end=82,
)


_SUBTRACTREQUEST = _descriptor.Descriptor(
  name='subtractRequest',
  full_name='subtractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='subtractRequest.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='subtractRequest.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_num1', full_name='subtractRequest._num1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_num2', full_name='subtractRequest._num2',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=84,
  serialized_end=157,
)


_RESULTREPLY = _descriptor.Descriptor(
  name='ResultReply',
  full_name='ResultReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ResultReply.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_number', full_name='ResultReply._number',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=159,
  serialized_end=204,
)

_ADDREQUEST.oneofs_by_name['_num1'].fields.append(
  _ADDREQUEST.fields_by_name['num1'])
_ADDREQUEST.fields_by_name['num1'].containing_oneof = _ADDREQUEST.oneofs_by_name['_num1']
_ADDREQUEST.oneofs_by_name['_num2'].fields.append(
  _ADDREQUEST.fields_by_name['num2'])
_ADDREQUEST.fields_by_name['num2'].containing_oneof = _ADDREQUEST.oneofs_by_name['_num2']
_SUBTRACTREQUEST.oneofs_by_name['_num1'].fields.append(
  _SUBTRACTREQUEST.fields_by_name['num1'])
_SUBTRACTREQUEST.fields_by_name['num1'].containing_oneof = _SUBTRACTREQUEST.oneofs_by_name['_num1']
_SUBTRACTREQUEST.oneofs_by_name['_num2'].fields.append(
  _SUBTRACTREQUEST.fields_by_name['num2'])
_SUBTRACTREQUEST.fields_by_name['num2'].containing_oneof = _SUBTRACTREQUEST.oneofs_by_name['_num2']
_RESULTREPLY.oneofs_by_name['_number'].fields.append(
  _RESULTREPLY.fields_by_name['number'])
_RESULTREPLY.fields_by_name['number'].containing_oneof = _RESULTREPLY.oneofs_by_name['_number']
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['subtractRequest'] = _SUBTRACTREQUEST
DESCRIPTOR.message_types_by_name['ResultReply'] = _RESULTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

subtractRequest = _reflection.GeneratedProtocolMessageType('subtractRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBTRACTREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:subtractRequest)
  })
_sym_db.RegisterMessage(subtractRequest)

ResultReply = _reflection.GeneratedProtocolMessageType('ResultReply', (_message.Message,), {
  'DESCRIPTOR' : _RESULTREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ResultReply)
  })
_sym_db.RegisterMessage(ResultReply)



_CAL = _descriptor.ServiceDescriptor(
  name='Cal',
  full_name='Cal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=206,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Cal.Add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_RESULTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='subtract',
    full_name='Cal.subtract',
    index=1,
    containing_service=None,
    input_type=_SUBTRACTREQUEST,
    output_type=_RESULTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAL)

DESCRIPTOR.services_by_name['Cal'] = _CAL

# @@protoc_insertion_point(module_scope)
